(() => {
  const $=s=>document.querySelector(s);let state=Storage.load(), graph, toastTimer;
  const session=()=>state.sessions[state.activeSessionId]; const n=v=>Number(v)||0;
  function persist(){Storage.save(state);render();}
  function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2300);}
  function applyTheme(){const mode=state.theme||'auto',dark=mode==='dark'||(mode==='auto'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);$('#themeSelect').value=mode;graph?.draw();}
  function renderSessions(){const sel=$('#sessionSelect');sel.innerHTML=Object.entries(state.sessions).map(([id,s])=>`<option value="${id}">${escapeHtml(s.name)}</option>`).join('');sel.value=state.activeSessionId;}
  function renderRates(){const s=session();$('#rateList').innerHTML=s.rates.map((rate,i)=>`<label class="rate-row"><input type="radio" name="rate" value="${i}" ${i===s.selectedRate?'checked':''}><input class="rate-input" data-index="${i}" type="number" step="0.1" value="${rate}"><span>枚/G</span></label>`).join('');}
  function renderConditions(){const s=session();$('#conditionList').innerHTML=s.conditions.map((c,i)=>`<div class="condition-editor interval-editor"><label>ゲーム間数<input data-condition="${i}" data-field="interval" type="number" min="1" value="${c.interval??Math.max(1,(c.end||0)-(c.start||0))}"></label><label>目標差枚<input data-condition="${i}" data-field="target" type="number" value="${c.target}"></label><button class="remove-condition" data-remove-condition="${i}" aria-label="条件を削除">×</button></div>`).join('');const evaluated=Conditions.evaluate(s.conditions,s.history);$('#conditionStatus').innerHTML=evaluated.map(x=>`<div class="status-item ${x.status==='達成'?'success':x.status==='未達'?'danger-status':''}"><strong>直近 ${x.interval}G</strong>　目標 +${x.target}枚：<b>${x.status}</b>${x.status==='達成'?'':`（あと${Math.ceil(x.remaining)}枚）`}<small>・${x.startGames}〜${x.currentGames}G：${signed(x.delta)}枚</small></div>`).join('');}
  function renderHistory(){const h=session().history;$('#historyCount').textContent=`${h.length} 件`;$(' #emptyHistory'.trim()).hidden=!!h.length;$('#historyBody').innerHTML=h.map((x,i)=>`<tr><td>${i+1}</td><td>${x.games}G</td><td>${x.rate>0?'+':''}${x.rate}</td><td>${signed(x.delta)}</td><td>${Math.round(x.total).toLocaleString()}</td><td>${escapeHtml(x.date)}</td><td><div class="row-actions"><button class="small-button ghost" data-edit="${i}">編集</button><button class="small-button danger-text" data-delete="${i}">削除</button></div></td></tr>`).join('');}
  function render(){const s=session();applyTheme();renderSessions();renderRates();$('#gameInput').value=s.gameInput;const rate=s.rates[s.selectedRate];$('#recordPreview').textContent=`${s.gameInput}G × ${rate>0?'+':''}${rate}枚/G = ${signed(s.gameInput*rate)}枚`;renderConditions();renderHistory();graph?.setData(s.history,Conditions.evaluate(s.conditions,s.history));}
  const signed=v=>`${v>=0?'+':''}${Math.round(v).toLocaleString()}`; const escapeHtml=s=>String(s).replace(/[&<>"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[x]));
  function record(){const s=session(),games=n(s.gameInput),rate=n(s.rates[s.selectedRate]);if(games<=0){toast('ゲーム数を入力してください');return;}const delta=games*rate,total=(s.history.at(-1)?.total||0)+delta,totalGames=(s.history.at(-1)?.totalGames||0)+games;s.history.push({id:crypto.randomUUID(),games,totalGames,rate,delta,total,date:new Date().toLocaleString('ja-JP')});s.gameInput=0;persist();toast('記録しました');}
  function editRow(i){const h=session().history[i],games=prompt('ゲーム数',h.games);if(games===null)return;const rate=prompt('純増（枚/G）',h.rate);if(rate===null)return;h.games=n(games);h.rate=n(rate);recalculate();persist();toast('履歴を更新しました');}
  function recalculate(){let total=0,totalGames=0;session().history.forEach(h=>{h.delta=h.games*h.rate;total+=h.delta;totalGames+=h.games;h.total=total;h.totalGames=totalGames;});}
  function resetSession(){if(!confirm('このセッションの履歴・条件・設定を初期化します。よろしいですか？'))return;const s=session();s.rates=[2.8,3,4.5,-1.5];s.selectedRate=0;s.gameInput=0;s.history=[];s.conditions=Storage.defaultConditions();persist();toast('初期化しました');}
  function bind(){document.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.step){session().gameInput=Math.max(0,n(session().gameInput)+n(btn.dataset.step));persist();}if(btn.id==='recordButton')record();if(btn.id==='addCondition'){if(session().conditions.length<4){session().conditions.push({start:0,end:100,target:500});persist();}else toast('条件は4件までです');}if(btn.dataset.removeCondition!==undefined){session().conditions.splice(n(btn.dataset.removeCondition),1);persist();}if(btn.dataset.delete!==undefined){if(confirm('この履歴を削除しますか？')){session().history.splice(n(btn.dataset.delete),1);recalculate();persist();}}if(btn.dataset.edit!==undefined)editRow(n(btn.dataset.edit));if(btn.id==='undoButton'){if(session().history.pop())persist();else toast('戻せる記録がありません');}if(btn.id==='resetButton')resetSession();if(btn.id==='newSession'){const name=prompt('新しいセッション名','新規セッション');if(name?.trim()){const id=crypto.randomUUID();state.sessions[id]={name:name.trim(),rates:[2.8,3,4.5,-1.5],selectedRate:0,gameInput:0,history:[],conditions:Storage.defaultConditions()};state.activeSessionId=id;persist();}}if(btn.id==='renameSession'){const name=prompt('セッション名',session().name);if(name?.trim()){session().name=name.trim();persist();}}if(btn.id==='deleteSession'){if(Object.keys(state.sessions).length===1){toast('最後のセッションは削除できません');return;}if(confirm(`「${session().name}」を削除しますか？`)){delete state.sessions[state.activeSessionId];state.activeSessionId=Object.keys(state.sessions)[0];persist();}}if(btn.id==='exportCsv')Csv.exportHistory(session().history);if(btn.id==='resetZoom')graph.reset();if(btn.id==='themeToggle'){state.theme=document.body.classList.contains('dark')?'light':'dark';persist();}});document.addEventListener('change',e=>{if(e.target.id==='sessionSelect'){state.activeSessionId=e.target.value;persist();}if(e.target.id==='themeSelect'){state.theme=e.target.value;persist();}if(e.target.name==='rate'){session().selectedRate=n(e.target.value);persist();}if(e.target.classList.contains('rate-input')){session().rates[n(e.target.dataset.index)]=n(e.target.value);persist();}if(e.target.dataset.condition!==undefined){session().conditions[n(e.target.dataset.condition)][e.target.dataset.field]=n(e.target.value);persist();}if(e.target.id==='importCsv'){const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const rows=Csv.parse(reader.result);if(!rows.length){toast('読み込めるCSV行がありません');return;}if(confirm(`${rows.length}件の履歴で置き換えますか？`)){session().history=rows;recalculate();persist();toast('CSVを読み込みました');}};reader.readAsText(f);e.target.value='';}});$('#gameInput').addEventListener('input',e=>{session().gameInput=Math.max(0,n(e.target.value));Storage.save(state);render();});$('#gameInput').addEventListener('wheel',e=>{e.preventDefault();session().gameInput=Math.max(0,n(session().gameInput)+(e.deltaY<0?1:-1));persist();},{passive:false});}
  document.addEventListener('DOMContentLoaded',()=>{Object.values(state.sessions).forEach(s=>{if(!s.conditions?.length)s.conditions=Storage.defaultConditions();s.conditions.forEach(c=>{if(c.interval===undefined){c.interval=Math.max(1,(c.end||0)-(c.start||0));delete c.start;delete c.end;}});});recalculate();Storage.save(state);graph=new MedalGraph.Graph($('#medalChart'),$('#chartTooltip'));bind();render();});
})();

